# Generated by Django 5.0.6 on 2024-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
