# Generated by Django 5.0.6 on 2024-05-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_alter_curso_nombre'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='precio_total',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='clase.estudiante'),
        ),
    ]
